# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PhotoPhly
                                 A QGIS plugin
 Drone 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-07
        copyright            : (C) 2021 by Lukas Winiwarter
        email                : lukas.winiwarter@uni-heidelberg.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PhotoPhly class from file PhotoPhly.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .photo_phly import PhotoPhly
    return PhotoPhly(iface)
